# Generated by Django 4.0.6 on 2022-07-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_album', models.CharField(max_length=50)),
                ('creador', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('arte', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cancion', models.CharField(max_length=50)),
                ('artista', models.CharField(max_length=50)),
                ('album', models.CharField(max_length=50)),
            ],
        ),
    ]
